### ISSUE TITLE
Build Erros

### ISSUE THREAD

**Issue by RogueMaster** [GMMan/flipperzero-vb-migrate#1]
Hi GMMan! With your new updates, there are some new errors on compile, not sure if you were aware, they are:

> In file included from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:10,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> applications/plugins/vbmigrate/lib/nfc/protocols/nfca.h:12:3: error: conflicting types for 'NfcaSignal'
>    12 | } NfcaSignal;
>       |   ^~~~~~~~~~
> In file included from firmware/targets/f7/furi_hal/furi_hal_nfc.h:16,
>                  from ./lib/nfc/nfc_device.h:8,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> ./lib/nfc/protocols/nfca.h:12:3: note: previous declaration of 'NfcaSignal' was here
>    12 | } NfcaSignal;
>       |   ^~~~~~~~~~
> In file included from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:10,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> applications/plugins/vbmigrate/lib/nfc/protocols/nfca.h:24:13: error: conflicting types for 'nfca_signal_alloc'
>    24 | NfcaSignal* nfca_signal_alloc();
>       |             ^~~~~~~~~~~~~~~~~
> In file included from firmware/targets/f7/furi_hal/furi_hal_nfc.h:16,
>                  from ./lib/nfc/nfc_device.h:8,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> ./lib/nfc/protocols/nfca.h:24:13: note: previous declaration of 'nfca_signal_alloc' was here
>    24 | NfcaSignal* nfca_signal_alloc();
>       |             ^~~~~~~~~~~~~~~~~
> In file included from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:10,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> applications/plugins/vbmigrate/lib/nfc/protocols/nfca.h:26:6: error: conflicting types for 'nfca_signal_free'
>    26 | void nfca_signal_free(NfcaSignal* nfca_signal);
>       |      ^~~~~~~~~~~~~~~~
> In file included from firmware/targets/f7/furi_hal/furi_hal_nfc.h:16,
>                  from ./lib/nfc/nfc_device.h:8,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> ./lib/nfc/protocols/nfca.h:26:6: note: previous declaration of 'nfca_signal_free' was here
>    26 | void nfca_signal_free(NfcaSignal* nfca_signal);
>       |      ^~~~~~~~~~~~~~~~
> In file included from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:10,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> applications/plugins/vbmigrate/lib/nfc/protocols/nfca.h:28:6: error: conflicting types for 'nfca_signal_encode'
>    28 | void nfca_signal_encode(NfcaSignal* nfca_signal, uint8_t* data, uint16_t bits, uint8_t* parity);
>       |      ^~~~~~~~~~~~~~~~~~
> In file included from firmware/targets/f7/furi_hal/furi_hal_nfc.h:16,
>                  from ./lib/nfc/nfc_device.h:8,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker_i.h:3,
>                  from applications/plugins/vbmigrate/lib/nfc/nfc_worker.c:1:
> ./lib/nfc/protocols/nfca.h:28:6: note: previous declaration of 'nfca_signal_encode' was here
>    28 | void nfca_signal_encode(NfcaSignal* nfca_signal, uint8_t* data, uint16_t bits, uint8_t* parity);
>       |      ^~~~~~~~~~~~~~~~~~
> 

If you think these errors are only on my build, please let me know if you know a way I can remove the errors and have it compile properly. Thank you!

**Comment by GMMan** [comment]
You should move the app out of tree. It's intended to be built from `applications_user`. Use the previous commit if you want to build it in-tree; the only changes made were to pull a copy of the NFC library to work around some dependency issues introduced with recent official releases.

**Comment by RogueMaster** [comment]
Ah ok, thank you!
