### ISSUE TITLE
Updates for latest firmwares

### ISSUE THREAD

**Issue by hedger** [GMMan/flipperzero-vb-migrate#2]
For latest firmware versions, app fails to build: https://github.com/flipperdevices/flipper-application-catalog/actions/runs/6263224472

Easy fix: `NFC_APP_EXTENSION` -> `NFC_APP_FILENAME_EXTENSION`

Also, when submitting the app to catalog, could you consider moving it from Tools section to NFC?

**Comment by GMMan** [comment]
Updated and PR submitted at https://github.com/flipperdevices/flipper-application-catalog/pull/155
