### ISSUE TITLE
Update the VB Migration Assistant app for the SDK version 0.98.2-rc f7

### ISSUE THREAD

**Issue by furippa** [GMMan/flipperzero-vb-migrate#5]
Hello! Your VB Migration Assistant app version 1.2 fails to build with the SDK version 0.98.2-rc f7. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/6499e4d7c3d2eeadb4bd3ff5/page)

**Comment by GMMan** [comment]
Cleaning up duplicate notifications
